# Generated by Django 2.2.1 on 2022-06-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('gisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gisement')),
            ],
        ),
    ]
